---
default:
  count : 100
  order : total
  cmd   : report
  hide_cmd_output : 1
language:
  rakudo :
    problem_set : perl6
    interp :
      - /usr/bin/perl6
      - /usr/bin/rakudo
  perl6 :
  perl5 :
    interp :
      - /usr/bin/perl
      - /usr/bin/env perl
  parrot:
    interp :
      - /usr/bin/parrot
  ruby:
    interp :
      - /usr/bin/ruby
  erlang:
    interp :
      - /usr/bin/erlang
  haskell :
    interp :
      - /usr/bin/env runhaskell
      - /usr/local/bin/runhaskell
  compiledtest:
    pre_run : echo 'PRE' >> /tmp/run
    post_run : echo 'POST' >> /tmp/run
    interp :
      - /bin/echo
  java :
    interp :
      - /usr/bin/env java
  scala : 
    interp : 
      - /opt/local/bin/scala
